openapi: 3.1.0
info:
  title: Minimal Reproducible Schema (YAML)
  version: 1.0.0
paths:
  /test:
    get:
      summary: Issue demonstration endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  # This causes error
                  ref:
                    type: string
